name: Lint
on:
  push:
    branches:
      - main

  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          args: --timeout=3m
